// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdwoawsgnijbguwzoicc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkd29hd3NnbmlqYmd1d3pvaWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODIxMzQsImV4cCI6MjA2MTA1ODEzNH0.VrXwhyY1lxJOtTW7mcMvGddplYRvSMDyaKhz3uzorlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);